# Generated by Django 4.0.5 on 2022-06-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null='True', upload_to='', verbose_name='Profile Image'),
            preserve_default='True',
        ),
    ]
