# Generated by Django 4.0.5 on 2022-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/jojopage-001.appspot.com/o/default%2Fno-profile-picture-icon-11.jpg?alt=media&token=7f8f1d08-6ce9-4ef5-b00e-0939e70895ed', null='True', upload_to='images/profile', verbose_name='Profile Image'),
        ),
    ]
