# Generated by Django 4.0.5 on 2022-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(default='static/blog/cool.jpg', upload_to=''),
        ),
    ]
