# Generated by Django 4.0.5 on 2022-07-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_post_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='summary',
        ),
    ]
